//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_ManagementEntities : DbContext
    {
        public Library_ManagementEntities()
            : base("name=Library_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookList_Table> BookList_Table { get; set; }
        public DbSet<Librarian_table> Librarian_table { get; set; }
        public DbSet<Occasion_Table> Occasion_Table { get; set; }
    }
}
